server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/indian_banks
    username: sudipbhandari
    password: johnlennon

