server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/indian_banks
    username: sudipbhandari
    password: johnlennon

logging:
  level:
    org.springframework: ERROR
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: app.log